services:
  api:
    image: chaserensberger/horizon:latest
    ports:
      - 1324:1323
    environment:
      - MONGODB_URI=
      - YOUTUBE_API_URL=
      - YOUTUBE_API_KEY=
      - FALLBACK_YOUTUBE_API_URL=
      - HORIZON_AUTH_KEY=
      - PRIMARY_ALLOWED_ROUTE=