services:
  api:
    image: chaserensberger/horizon:latest
    ports:
      - 1324:1323
    environment:
      - MONGODB_URI=mongodb://127.0.0.1:27017
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - horizon-mongo:/data

volumes:
  horizon-mongo:
